name: BasilExplore
version: '${version}'
main: io.github.transdryad.basilexplore.BasilExplore
api-version: '1.21.1'
author: Transdryad
depend: [Citizens]
commands:
  home:
    description: Teleport player to their home in future.
    usage: /<command>
  warrior:
    description: spawns a warrior npc
    usage: /<command>