name: BasilExplore
version: '${version}'
main: io.github.transdryad.basilexplore.BasilExplore
api-version: '1.20.6'
author: Transdryad
commands:
  kit:
    description: Gives a player the standard BasilCraft Starter Kit.
    usage: /kit
    permission: basilExplore.starterKit
